### ISSUE TITLE
Textarea on items not expanding on Firefox

### ISSUE THREAD

**Issue by garciadelcastillo** [nonoesp/laravel-folio#1]
On creation/editing of an item, the textarea doesn't automatically expand on Firefox, but rather stays contracted with a scroll bar. 

![image](https://user-images.githubusercontent.com/3866478/36648101-cd91a194-1a5c-11e8-8f0a-da4fc9411311.png)

It works fine on Chrome. Tested on Firefox 58.0.2 (Windows 8).

**Comment by nonoesp** [comment]
Addressed this issue on pull request https://github.com/nonoesp/laravel-folio/pull/5 — textarea expansion works now with Firefox =). Closing the issue now.
