### ISSUE TITLE
Preview doesn't save the item

### ISSUE THREAD

**Issue by garciadelcastillo** [nonoesp/laravel-folio#3]
When creating/editing an item, if `Preview` is pressed but content has not been saved, the content is lost. 

It would be ideal to have `Preview` raise an alert that there are unsaved changes, or automatically save before preview, and take advantage of the amazing versioning system... ;)

**Comment by nonoesp** [comment]
This issue has been addressed on pull request https://github.com/nonoesp/laravel-folio/pull/7. Now you are warned if you try to leave the Item edit page with unsaved changes.
