### ISSUE TITLE
Item deletion

### ISSUE THREAD

**Issue by garciadelcastillo** [nonoesp/laravel-folio#4]
It would be awesome to be able to delete items :)

**Comment by nonoesp** [comment]
A new contextual button inside the Item Edit page is available to permanently delete a Folio item. This page will first ask for confirmation and then remove the Folio item from the database forever. (Changes are addressed on pull request https://github.com/nonoesp/laravel-folio/pull/8.)

#### Contextual menu "X" button

<img width="256" alt="screen shot 2018-03-13 at 10 42 57 pm" src="https://user-images.githubusercontent.com/1243210/37380629-e40b4ed8-270f-11e8-9697-e0bb154c2d5d.png">

#### Confirmation page

<img width="509" alt="screen shot 2018-03-13 at 10 43 14 pm" src="https://user-images.githubusercontent.com/1243210/37380640-f0dbc1d8-270f-11e8-9609-22acbb83dc17.png">
